{
	"type": "feature_profile",
	"disabled_features": [
		"3d",
		"asset_lib",
		"import_dock",
		"history_dock"
	],
	"disabled_classes": [
		"Node3D",
		"Camera3D",
		"MeshInstance3D",
		"CSGShape3D",
		"GridMap",
		"GPUParticles3D",
		"CPUParticles3D",
		"XROrigin3D",
		"XRCamera3D",
		"XRController3D",
		"AudioStreamPlayer3D",
		"CollisionObject3D",
		"RigidBody3D",
		"CharacterBody3D",
		"StaticBody3D",
		"Area3D",
		"NavigationRegion3D",
		"NavigationAgent3D",
		"Light3D",
		"DirectionalLight3D",
		"OmniLight3D",
		"SpotLight3D",
		"WorldEnvironment",
		"VoxelGI",
		"LightmapGI",
		"ReflectionProbe",
		"Decal",
		"FogVolume",
		"GPUParticlesCollision3D",
		"SoftBody3D",
		"VehicleBody3D",
		"VehicleWheel3D",
		"Path3D",
		"PathFollow3D",
		"Skeleton3D",
		"BoneAttachment3D",
		"ImporterMeshInstance3D",
		"MultiMeshInstance3D",
		"Sprite3D",
		"AnimatedSprite3D",
		"Label3D",
		"VideoStreamPlayer"
	],
	"disabled_editors": [],
	"disabled_properties": []
}
