extends AutoworkTest


func test_007_list_cli_candidates_includes_blazium_env() -> void:
	var prev := OS.get_environment("BLAZIUM")
	OS.set_environment("BLAZIUM", "C:/Program Files/Blazium" if OS.get_name() == "Windows" else "/opt/blazium")
	var candidates: PackedStringArray = HubCli.list_cli_candidates()
	assert_true(candidates.size() >= 2, "has candidates")
	var joined := "\n".join(candidates)
	if OS.get_name() == "Windows":
		assert_true(joined.contains("C:/Program Files/Blazium") or joined.contains("C:\\Program Files\\Blazium"), "BLAZIUM root probed")
		assert_true(joined.contains("blazium-cli.exe"), "windows cli name")
	else:
		assert_true(joined.contains("/opt/blazium/bin/blazium-cli"), "linux BLAZIUM bin")
	assert_true(joined.contains("blazium-cli"), "PATH fallback present")
	# Bare names must be last among duplicates of the same basename class.
	var last: String = candidates[candidates.size() - 1]
	assert_true(last == "blazium-cli" or last == "blazium-cli.exe", "bare PATH name last")
	OS.set_environment("BLAZIUM", prev)


func test_007_list_cli_candidates_includes_exe_relative() -> void:
	var exe_dir := OS.get_executable_path().get_base_dir()
	var derived := HubCli.install_root_from_exe()
	var candidates: PackedStringArray = HubCli.list_cli_candidates()
	assert_true(candidates.size() >= 2, "has candidates")
	var joined := "\n".join(candidates)
	if OS.get_name() == "Windows":
		var sibling := exe_dir.path_join("blazium-cli.exe")
		assert_true(joined.contains(sibling), "exe-dir sibling probed: %s" % sibling)
		if not derived.is_empty():
			assert_true(
				joined.contains(derived.path_join("blazium-cli.exe")),
				"exe-derived install root probed: %s" % derived
			)
	else:
		var sibling := exe_dir.path_join("blazium-cli")
		assert_true(joined.contains(sibling), "exe-dir sibling probed: %s" % sibling)
		if not derived.is_empty():
			var from_root := derived.path_join("bin").path_join("blazium-cli")
			var from_root_flat := derived.path_join("blazium-cli")
			assert_true(
				joined.contains(from_root) or joined.contains(from_root_flat),
				"exe-derived install root probed: %s" % derived
			)
	var last: String = candidates[candidates.size() - 1]
	assert_true(last == "blazium-cli" or last == "blazium-cli.exe", "bare PATH name last")


func test_007_packaging_shims_exist() -> void:
	var presets := FileAccess.get_file_as_string("res://export_presets.cfg")
	assert_true(presets.contains("binary_format/embed_pck=true"), "pack is embedded in the Hub exe")
	assert_true(not presets.contains("binary_format/embed_pck=false"), "no sidecar-only export presets")
	assert_true(FileAccess.file_exists("res://packaging/windows/blazium.cmd"), "blazium.cmd")
	assert_true(FileAccess.file_exists("res://packaging/windows/blazium-hub.cmd"), "blazium-hub.cmd")
	assert_true(FileAccess.file_exists("res://packaging/linux/blazium.sh"), "profile.d blazium.sh")
	assert_true(FileAccess.file_exists("res://ci/smoke_install_linux.sh"), "linux smoke")
	assert_true(FileAccess.file_exists("res://ci/smoke_install_windows.ps1"), "windows smoke")
	assert_true(FileAccess.file_exists("res://ci/hub_scons.env"), "hub scons allowlist")
	var scons := FileAccess.get_file_as_string("res://ci/hub_scons.env")
	assert_true(scons.contains("HUB_SCONS_COMMON="), "HUB_SCONS_COMMON present")
	assert_true(scons.contains("module_noise_enabled=yes"), "slim Hub builds include noise for FastNoiseLite")
	var cmd := FileAccess.get_file_as_string("res://packaging/windows/blazium.cmd")
	assert_true(cmd.contains("blazium-cli.exe"), "blazium.cmd forwards to CLI")
	var hub_cmd := FileAccess.get_file_as_string("res://packaging/windows/blazium-hub.cmd")
	assert_true(hub_cmd.contains("BlaziumHub.exe"), "blazium-hub.cmd launches Hub")
	var profile := FileAccess.get_file_as_string("res://packaging/linux/blazium.sh")
	assert_true(profile.contains("BLAZIUM=/opt/blazium"), "sets BLAZIUM")
	assert_true(profile.contains("${BLAZIUM}/bin") or profile.contains("$BLAZIUM/bin"), "prepends bin to PATH")
	var iss := FileAccess.get_file_as_string("res://packaging/windows/blazium-hub.iss")
	assert_true(iss.contains('/DIR='), "documents silent /DIR=")
	assert_true(iss.contains("/LAUNCH"), "documents silent /LAUNCH")
	assert_true(iss.contains("ShouldLaunchAfterSilent"), "silent launch Check helper")
	assert_true(iss.contains("skipifnotsilent"), "silent-only Run entry")
	assert_true(iss.contains("CloseApplications=yes"), "closes Hub for self-update")
	assert_true(iss.contains("PrivilegesRequired=admin"), "requires admin / machine-wide install")
	assert_true(not iss.contains("PrivilegesRequiredOverridesAllowed="), "disallows /CURRENTUSER override")
	assert_true(iss.contains("Visit Blazium.app"), "finish page Visit Blazium.app checkbox")
	assert_true(iss.contains("shellexec"), "Visit Blazium.app uses shellexec")
	assert_true(iss.contains("ValueData: \"{app}\""), "BLAZIUM uses {app}")
	assert_true(iss.contains("UsePreviousAppDir=yes"), "keeps prior custom dir")
	assert_true(iss.contains("blazium-cli.exe"), "protocol uses blazium-cli")
	assert_true(iss.contains("handle-uri"), "protocol invokes handle-uri")
	assert_true(iss.contains("hub-remote ensure"), "installer ensures via blazium-cli hub-remote")
	assert_true(iss.contains("EnsureHubRemoteSecrets"), "installer Code helper ensures secrets")
	assert_true(iss.contains("ExecAsOriginalUser"), "user ensure runs as original user")
	assert_true(iss.contains("--ensure-hub-remote"), "installer keeps Hub ensure fallback")
	assert_true(iss.contains("hub_remote.json"), "installer targets hub_remote.json path")
	assert_true(iss.contains("IsUpgradeInstall"), "detects fresh vs upgrade")
	assert_true(iss.contains("InstallKind"), "records InstallKind in registry")
	assert_true(iss.contains("/INSTALLTOOLCHAIN"), "silent toolchain opt-in")
	assert_true(iss.contains("/NOANALYTICS"), "silent analytics opt-out")
	assert_true(iss.contains("Help improve Blazium Hub with anonymous analytics"), "analytics task caption")
	assert_true(iss.contains("hub_installed"), "posts hub_installed")
	assert_true(iss.contains("hub_upgraded"), "posts hub_upgraded")
	assert_true(iss.contains("WinHttp.WinHttpRequest.5.1"), "WinHTTP install analytics")
	assert_true(iss.contains("WantAnalytics"), "analytics opt-in helper")
	assert_true(iss.contains("PersistHubAnalyticsConsent"), "writes hub_settings.cfg")
	assert_true(iss.contains("embed_pck=true"), "installer documents embedded pack")
	assert_true(iss.contains("\\VERSION\""), "installer ships Hub VERSION")
	var nfpm := FileAccess.get_file_as_string("res://packaging/linux/nfpm.yaml")
	assert_true(nfpm.contains("crash_reporter.version"), "linux package ships crash_reporter.version")
	assert_true(nfpm.contains("/opt/blazium/VERSION"), "linux package ships Hub VERSION")
	var fetch_cr := FileAccess.get_file_as_string("res://ci/fetch_latest_crash_reporter.py")
	assert_true(fetch_cr.contains("write_version_sidecar"), "fetch writes crash_reporter.version")
	assert_true(fetch_cr.contains("crash_reporter.version"), "version sidecar name")
	assert_true(iss.contains("InitializeWizard"), "custom toolchain wizard pages")
	assert_true(iss.contains("Blazium Toolchain (optional)"), "optional toolchain page")
	assert_true(iss.contains("Toolchain License Agreement"), "separate GPL license page")
	assert_true(iss.contains("toolchain-LICENSE.txt"), "vendors toolchain GPL")
	assert_true(iss.contains("toolchain-features.txt"), "vendors toolchain catalog")
	assert_true(iss.contains("WantToolchain"), "toolchain opt-in helper")
	assert_true(iss.contains("InstallToolchainViaCli"), "post-install CLI toolchain apply")
	assert_true(iss.contains("update apply --product toolchain"), "invokes CLI toolchain apply")
	assert_true(iss.contains("--install-root"), "passes install root to CLI apply")
	assert_true(FileAccess.file_exists("res://packaging/windows/toolchain-LICENSE.txt"), "toolchain LICENSE vendored")
	assert_true(FileAccess.file_exists("res://packaging/windows/toolchain-features.txt"), "toolchain features vendored")
	assert_true(FileAccess.file_exists("res://packaging/linux/blazium-uri.desktop"), "linux URI desktop")
	var uri_desktop := FileAccess.get_file_as_string("res://packaging/linux/blazium-uri.desktop")
	assert_true(uri_desktop.contains("blazium-cli handle-uri"), "linux URI desktop runs CLI")
	var postinst := FileAccess.get_file_as_string("res://packaging/linux/postinst")
	assert_true(postinst.contains("--ensure-hub-remote"), "linux postinst ensures hub_remote")
	assert_true(postinst.contains("/etc/blazium/hub_remote.json"), "linux machine secret path")
	assert_true(postinst.contains("BLAZIUM_INSTALL_TOOLCHAIN"), "linux toolchain env opt-in")
	assert_true(postinst.contains("update apply --product toolchain"), "linux postinst CLI toolchain apply")
	assert_true(postinst.contains("/usr/bin/blazium-toolchain"), "linux toolchain symlink")
	assert_true(postinst.contains("BLAZIUM_NO_ANALYTICS"), "linux analytics opt-out")
	assert_true(postinst.contains("hub_installed"), "linux posts hub_installed")
	assert_true(postinst.contains("hub_upgraded"), "linux posts hub_upgraded")
	var smoke_win := FileAccess.get_file_as_string("res://ci/smoke_install_windows.ps1")
	assert_true(smoke_win.contains("/NOANALYTICS"), "windows smoke skips production analytics")
	assert_true(smoke_win.contains("--self-test"), "windows smoke runs hub self-test")
	assert_true(smoke_win.contains("crash_reporter.version"), "windows smoke checks crash reporter version file")
	assert_true(smoke_win.contains("VERSION"), "windows smoke checks Hub VERSION")
	var smoke_linux := FileAccess.get_file_as_string("res://ci/smoke_install_linux.sh")
	assert_true(smoke_linux.contains("BLAZIUM_NO_ANALYTICS"), "linux smoke skips production analytics")
	assert_true(smoke_linux.contains("--self-test"), "linux smoke runs hub self-test")
	assert_true(smoke_linux.contains("crash_reporter.version"), "linux smoke checks crash reporter version file")
	assert_true(smoke_linux.contains("/opt/blazium/VERSION"), "linux smoke checks Hub VERSION")
	var postrm := FileAccess.get_file_as_string("res://packaging/linux/postrm")
	assert_true(postrm.contains("/etc/blazium"), "linux postrm removes /etc/blazium")
	assert_true(postrm.contains("/usr/bin/blazium-toolchain"), "linux postrm removes toolchain symlink")

